// <auto-generated />
using System;
using CSMS_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSMS_API.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20251101032417_9")]
    partial class _9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSMS_API.Models.BusinessUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BusinessUnit");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "Binugao, Toril, Davao City",
                            Name = "ABFI"
                        });
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnitLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BusinessUnitID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BusinessUnitID");

                    b.ToTable("BusinessUnitLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.CompanyLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.DepartmentLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.PositionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.RepresentativeLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RepresentativeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RepresentativeID");

                    b.ToTable("RepresentativeLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CSMS_API.Models.RoleLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UpdatedID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleLog");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BusinessUnitID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BusinessUnitID");

                    b.HasIndex("PositionID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BusinessUnitID = 1,
                            FirstName = "James",
                            LastName = "Tabilog",
                            Password = "$2a$11$V/JTbg48n4h3Zs4V3n5PMezUMbqJYGEhl7vN6gOQ39gxWTEEx0Q9C",
                            RecordStatus = 1,
                            Username = "211072"
                        });
                });

            modelBuilder.Entity("CSMS_API.Models.UserLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLog");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnitLog", b =>
                {
                    b.HasOne("CSMS_API.Models.BusinessUnit", "BusinessUnit")
                        .WithMany("BusinessUnitLog")
                        .HasForeignKey("BusinessUnitID");

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("CSMS_API.Models.CompanyLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Company", "Company")
                        .WithMany("CompanyLog")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.DepartmentLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Department", "Department")
                        .WithMany("DepartmentLog")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.HasOne("CSMS_API.Models.Department", "Department")
                        .WithMany("Position")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.PositionLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Position", "Position")
                        .WithMany("PositionLog")
                        .HasForeignKey("PositionID");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.HasOne("CSMS_API.Models.Company", "Company")
                        .WithMany("Representative")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.RepresentativeLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Representative", "Representative")
                        .WithMany("RepresentativeLog")
                        .HasForeignKey("RepresentativeID");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.RoleLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Role", "Role")
                        .WithMany("RoleLog")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.HasOne("CSMS_API.Models.BusinessUnit", "BusinessUnit")
                        .WithMany("User")
                        .HasForeignKey("BusinessUnitID");

                    b.HasOne("CSMS_API.Models.Position", "Position")
                        .WithMany("User")
                        .HasForeignKey("PositionID");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.UserLog", b =>
                {
                    b.HasOne("CSMS_API.Models.User", "User")
                        .WithMany("UserLog")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRole", b =>
                {
                    b.HasOne("CSMS_API.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleID");

                    b.HasOne("CSMS_API.Models.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserID");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnit", b =>
                {
                    b.Navigation("BusinessUnitLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.Company", b =>
                {
                    b.Navigation("CompanyLog");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.Department", b =>
                {
                    b.Navigation("DepartmentLog");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.Navigation("PositionLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.Navigation("RepresentativeLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Role", b =>
                {
                    b.Navigation("RoleLog");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.Navigation("UserLog");

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
