// <auto-generated />
using System;
using CSMS_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CSMS_API.Migrations
{
    [DbContext(typeof(DB))]
    [Migration("20251107004007_10")]
    partial class _10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CSMS_API.Models.BusinessUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("BusinessUnit");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Location = "Binugao, Toril, Davao City",
                            Name = "ABFI"
                        });
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnitLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BusinessUnitID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BusinessUnitID");

                    b.ToTable("BusinessUnitLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Category", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CSMS_API.Models.CategoryLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("CategoryLog");
                });

            modelBuilder.Entity("CSMS_API.Models.ColdStorage", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("ColdStorage");
                });

            modelBuilder.Entity("CSMS_API.Models.ColdStorageLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ColdStorageID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ColdStorageID");

                    b.ToTable("ColdStorageLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.CompanyLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("CompanyLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.DepartmentLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("DepartmentLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Pallet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pallet");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PalletID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PalletID");

                    b.ToTable("PalletLog");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletPosition", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ColdStorageID")
                        .HasColumnType("int");

                    b.Property<string>("Column")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Side")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wing")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ColdStorageID");

                    b.ToTable("PalletPosition");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletPositionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PalletPositionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PalletPositionID");

                    b.ToTable("PalletPositionLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.PositionLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductPackaging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Variant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CSMS_API.Models.ProductLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.ToTable("ProductLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Receiving", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ApproverID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ArrivalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CVNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("UnloadingEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnloadingStart")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ApproverID");

                    b.HasIndex("CreatorID");

                    b.ToTable("Receiving");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<int?>("DUQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QuantityInPallet")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivingID")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("CreatorID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ReceivingID");

                    b.ToTable("ReceivingDetail");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingDetailLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ReceivingDetailID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReceivingDetailID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("ReceivingDetailLog");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ReceivingID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReceivingID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("ReceivingLog");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingPlacement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ApproverID")
                        .HasColumnType("int");

                    b.Property<string>("CrateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PalletID")
                        .HasColumnType("int");

                    b.Property<int?>("PalletPositionID")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivingDetailID")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivingProductID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TaggingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("PalletID");

                    b.HasIndex("PalletPositionID");

                    b.HasIndex("ReceivingDetailID");

                    b.HasIndex("ReceivingProductID");

                    b.ToTable("ReceivingPlacement");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingPlacementLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ReceivingPlacementID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReceivingPlacementID");

                    b.ToTable("ReceivingPlacementLog");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingProduct", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ProductID")
                        .HasColumnType("int");

                    b.Property<int?>("ReceivingID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<int?>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<double?>("TotalWeight")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("ProductID");

                    b.HasIndex("ReceivingID");

                    b.ToTable("ReceivingProduct");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingProductLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ReceivingProductID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReceivingProductID");

                    b.HasIndex("UpdaterID");

                    b.ToTable("ReceivingProductLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("TelephoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.RepresentativeLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RepresentativeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RepresentativeID");

                    b.ToTable("RepresentativeLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CSMS_API.Models.RoleLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("RoleLog");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BusinessUnitID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PositionID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BusinessUnitID");

                    b.HasIndex("PositionID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BusinessUnitID = 1,
                            FirstName = "James",
                            LastName = "Tabilog",
                            Password = "$2a$11$V/JTbg48n4h3Zs4V3n5PMezUMbqJYGEhl7vN6gOQ39gxWTEEx0Q9C",
                            RecordStatus = 1,
                            Username = "211072"
                        });
                });

            modelBuilder.Entity("CSMS_API.Models.UserLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("UserLog");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRole", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("AssignedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignerID")
                        .HasColumnType("int");

                    b.Property<int?>("RecordStatus")
                        .HasColumnType("int");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRoleLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdaterID")
                        .HasColumnType("int");

                    b.Property<int?>("UserRoleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UserRoleID");

                    b.ToTable("UserRoleLog");
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnitLog", b =>
                {
                    b.HasOne("CSMS_API.Models.BusinessUnit", "BusinessUnit")
                        .WithMany("BusinessUnitLog")
                        .HasForeignKey("BusinessUnitID");

                    b.Navigation("BusinessUnit");
                });

            modelBuilder.Entity("CSMS_API.Models.CategoryLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Category", "Category")
                        .WithMany("CategoryLog")
                        .HasForeignKey("CategoryID");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CSMS_API.Models.ColdStorageLog", b =>
                {
                    b.HasOne("CSMS_API.Models.ColdStorage", "ColdStorage")
                        .WithMany("ColdStorageLog")
                        .HasForeignKey("ColdStorageID");

                    b.Navigation("ColdStorage");
                });

            modelBuilder.Entity("CSMS_API.Models.CompanyLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Company", "Company")
                        .WithMany("CompanyLog")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.DepartmentLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Department", "Department")
                        .WithMany("DepartmentLog")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Pallet", "Pallet")
                        .WithMany("PalletLog")
                        .HasForeignKey("PalletID");

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletPosition", b =>
                {
                    b.HasOne("CSMS_API.Models.ColdStorage", "ColdStorage")
                        .WithMany("PalletPosition")
                        .HasForeignKey("ColdStorageID");

                    b.Navigation("ColdStorage");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletPositionLog", b =>
                {
                    b.HasOne("CSMS_API.Models.PalletPosition", "PalletPosition")
                        .WithMany("PalletPositionLog")
                        .HasForeignKey("PalletPositionID");

                    b.Navigation("PalletPosition");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.HasOne("CSMS_API.Models.Department", "Department")
                        .WithMany("Position")
                        .HasForeignKey("DepartmentID");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CSMS_API.Models.PositionLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Position", "Position")
                        .WithMany("PositionLog")
                        .HasForeignKey("PositionID");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.Product", b =>
                {
                    b.HasOne("CSMS_API.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryID");

                    b.HasOne("CSMS_API.Models.Company", "Company")
                        .WithMany("Product")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.ProductLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Product", "Product")
                        .WithMany("ProductLog")
                        .HasForeignKey("ProductID");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSMS_API.Models.Receiving", b =>
                {
                    b.HasOne("CSMS_API.Models.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverID");

                    b.HasOne("CSMS_API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.Navigation("Approver");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingDetail", b =>
                {
                    b.HasOne("CSMS_API.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorID");

                    b.HasOne("CSMS_API.Models.Product", "Product")
                        .WithMany("ReceivingDetail")
                        .HasForeignKey("ProductID");

                    b.HasOne("CSMS_API.Models.Receiving", "Receiving")
                        .WithMany("ReceivingDetail")
                        .HasForeignKey("ReceivingID");

                    b.Navigation("Creator");

                    b.Navigation("Product");

                    b.Navigation("Receiving");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingDetailLog", b =>
                {
                    b.HasOne("CSMS_API.Models.ReceivingDetail", "ReceivingDetail")
                        .WithMany("ReceivingDetailLog")
                        .HasForeignKey("ReceivingDetailID");

                    b.HasOne("CSMS_API.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("ReceivingDetail");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Receiving", "Receiving")
                        .WithMany("ReceivingLog")
                        .HasForeignKey("ReceivingID");

                    b.HasOne("CSMS_API.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("Receiving");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingPlacement", b =>
                {
                    b.HasOne("CSMS_API.Models.Pallet", "Pallet")
                        .WithMany("ReceivingPlacement")
                        .HasForeignKey("PalletID");

                    b.HasOne("CSMS_API.Models.PalletPosition", "PalletPosition")
                        .WithMany("ReceivingPlacement")
                        .HasForeignKey("PalletPositionID");

                    b.HasOne("CSMS_API.Models.ReceivingDetail", "ReceivingDetail")
                        .WithMany("ReceivingPlacement")
                        .HasForeignKey("ReceivingDetailID");

                    b.HasOne("CSMS_API.Models.ReceivingProduct", "ReceivingProduct")
                        .WithMany("ReceivingPlacement")
                        .HasForeignKey("ReceivingProductID");

                    b.Navigation("Pallet");

                    b.Navigation("PalletPosition");

                    b.Navigation("ReceivingDetail");

                    b.Navigation("ReceivingProduct");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingPlacementLog", b =>
                {
                    b.HasOne("CSMS_API.Models.ReceivingPlacement", "ReceivingPlacement")
                        .WithMany("ReceivingPlacementLog")
                        .HasForeignKey("ReceivingPlacementID");

                    b.Navigation("ReceivingPlacement");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingProduct", b =>
                {
                    b.HasOne("CSMS_API.Models.Product", "Product")
                        .WithMany("ReceivingProduct")
                        .HasForeignKey("ProductID");

                    b.HasOne("CSMS_API.Models.Receiving", "Receiving")
                        .WithMany("ReceivingProduct")
                        .HasForeignKey("ReceivingID");

                    b.Navigation("Product");

                    b.Navigation("Receiving");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingProductLog", b =>
                {
                    b.HasOne("CSMS_API.Models.ReceivingProduct", "ReceivingProduct")
                        .WithMany("ReceivingProductLog")
                        .HasForeignKey("ReceivingProductID");

                    b.HasOne("CSMS_API.Models.User", "Updater")
                        .WithMany()
                        .HasForeignKey("UpdaterID");

                    b.Navigation("ReceivingProduct");

                    b.Navigation("Updater");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.HasOne("CSMS_API.Models.Company", "Company")
                        .WithMany("Representative")
                        .HasForeignKey("CompanyID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CSMS_API.Models.RepresentativeLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Representative", "Representative")
                        .WithMany("RepresentativeLog")
                        .HasForeignKey("RepresentativeID");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.RoleLog", b =>
                {
                    b.HasOne("CSMS_API.Models.Role", "Role")
                        .WithMany("RoleLog")
                        .HasForeignKey("RoleID");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.HasOne("CSMS_API.Models.BusinessUnit", "BusinessUnit")
                        .WithMany("User")
                        .HasForeignKey("BusinessUnitID");

                    b.HasOne("CSMS_API.Models.Position", "Position")
                        .WithMany("User")
                        .HasForeignKey("PositionID");

                    b.Navigation("BusinessUnit");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.UserLog", b =>
                {
                    b.HasOne("CSMS_API.Models.User", "User")
                        .WithMany("UserLog")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRole", b =>
                {
                    b.HasOne("CSMS_API.Models.Role", "Role")
                        .WithMany("UserRole")
                        .HasForeignKey("RoleID");

                    b.HasOne("CSMS_API.Models.User", "User")
                        .WithMany("UserRole")
                        .HasForeignKey("UserID");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.UserRoleLog", b =>
                {
                    b.HasOne("CSMS_API.Models.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleID");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CSMS_API.Models.BusinessUnit", b =>
                {
                    b.Navigation("BusinessUnitLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.Category", b =>
                {
                    b.Navigation("CategoryLog");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CSMS_API.Models.ColdStorage", b =>
                {
                    b.Navigation("ColdStorageLog");

                    b.Navigation("PalletPosition");
                });

            modelBuilder.Entity("CSMS_API.Models.Company", b =>
                {
                    b.Navigation("CompanyLog");

                    b.Navigation("Product");

                    b.Navigation("Representative");
                });

            modelBuilder.Entity("CSMS_API.Models.Department", b =>
                {
                    b.Navigation("DepartmentLog");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("CSMS_API.Models.Pallet", b =>
                {
                    b.Navigation("PalletLog");

                    b.Navigation("ReceivingPlacement");
                });

            modelBuilder.Entity("CSMS_API.Models.PalletPosition", b =>
                {
                    b.Navigation("PalletPositionLog");

                    b.Navigation("ReceivingPlacement");
                });

            modelBuilder.Entity("CSMS_API.Models.Position", b =>
                {
                    b.Navigation("PositionLog");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CSMS_API.Models.Product", b =>
                {
                    b.Navigation("ProductLog");

                    b.Navigation("ReceivingDetail");

                    b.Navigation("ReceivingProduct");
                });

            modelBuilder.Entity("CSMS_API.Models.Receiving", b =>
                {
                    b.Navigation("ReceivingDetail");

                    b.Navigation("ReceivingLog");

                    b.Navigation("ReceivingProduct");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingDetail", b =>
                {
                    b.Navigation("ReceivingDetailLog");

                    b.Navigation("ReceivingPlacement");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingPlacement", b =>
                {
                    b.Navigation("ReceivingPlacementLog");
                });

            modelBuilder.Entity("CSMS_API.Models.ReceivingProduct", b =>
                {
                    b.Navigation("ReceivingPlacement");

                    b.Navigation("ReceivingProductLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Representative", b =>
                {
                    b.Navigation("RepresentativeLog");
                });

            modelBuilder.Entity("CSMS_API.Models.Role", b =>
                {
                    b.Navigation("RoleLog");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CSMS_API.Models.User", b =>
                {
                    b.Navigation("UserLog");

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
